language: node_js
node_js:
- '0.10'
env:
  global:
  - SAUCE_USERNAME=angular-ci
  - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987
  - LOGS_DIR=/tmp/protractor-build/logs
  - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
  - secure: HrFYAjnxN7hwcrdOJ11hOZ5nm1j1zjFn93I13bVCZDLdKjfw82cAlTN7hYyOvfiJ8izOUEJK3EX3OSX+arKTRoS/EQ7gl02Oo8Gy97HDUNRAeu/RfofGMMnX++8kMVyucCf7pPS4hkjEsBsHMuj06gu1jqUW7GiqGxT8EpxRqFA=
before_script:
- mkdir -p $LOGS_DIR
- ./node_modules/.bin/bower install
- ./scripts/sauce_connect_setup.sh
- ./scripts/wait_for_browser_provider.sh
script:
- ./scripts/testonsauce.sh
after_script:
- ./scripts/travis_update_dist_branch.sh
- ./scripts/print_logs.sh
